# Generated by Django 5.2.5 on 2025-08-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Offers",
            new_name="Offer",
        ),
    ]
